
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # Database configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/netdeal?useSSL=false&serverTimezone=UTC
    username: username
    password: password

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:database/migrations
    url: jdbc:mysql://localhost:3306/netdeal
    schemas: netdeal
    defaultSchema: netdeal
    user: username
    password: password
    baseline-on-migrate: true
